import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";

import type { Client, Invoice, Quote } from "./types";

type BuildArgs = {
  title: string;
  number: string;
  meta: { label: string; value: string }[];
  itemsHtml?: string;
  total?: string;
  notes?: string;
  client?: Client | null;
  logoUri?: string | null;
  businessName?: string | null;
  accentColor?: string;
};

function escapeHtml(input: string): string {
  return input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function buildHtml(args: BuildArgs): string {
  const accent = args.accentColor || "#0F172A";
  const logoBlock = args.logoUri
    ? `<img src="${args.logoUri}" alt="logo" style="width:72px;height:72px;object-fit:contain;border-radius:8px;border:1px solid #E2E8F0;padding:4px;" />`
    : "";
  const clientBlock = args.client
    ? `
      <div>
        <div class="muted">Bill to</div>
        <div class="value">${escapeHtml(args.client.name || "")}</div>
        ${args.client.company ? `<div class="muted">${escapeHtml(args.client.company)}</div>` : ""}
        ${args.client.email ? `<div class="muted">${escapeHtml(args.client.email)}</div>` : ""}
        ${args.client.phone ? `<div class="muted">${escapeHtml(args.client.phone)}</div>` : ""}
      </div>`
    : "";
  const businessLine = args.businessName
    ? `<div class="brand-name">${escapeHtml(args.businessName)}</div>`
    : "";
  const metaRows = args.meta
    .map(
      (m) =>
        `<div class="meta-row"><span class="muted">${escapeHtml(m.label)}</span><span class="value">${escapeHtml(m.value)}</span></div>`,
    )
    .join("");
  return `<!doctype html>
<html><head><meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #0F172A; padding: 40px; max-width: 800px; margin: 0 auto; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; gap: 24px; margin-bottom: 32px; }
  .brand-name { font-size: 14px; color: #475569; font-weight: 600; margin-top: 8px; }
  .doc-title { color: ${accent}; font-size: 32px; font-weight: 800; letter-spacing: -0.5px; margin: 0; }
  .doc-number { font-size: 14px; color: #475569; margin-top: 4px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 24px; }
  .muted { color: #64748B; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 600; }
  .value { color: #0F172A; font-size: 15px; font-weight: 600; }
  .meta-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #F1F5F9; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; margin: 24px 0; }
  th, td { text-align: left; padding: 12px; font-size: 14px; }
  th { background: #F8FAFC; color: #475569; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; }
  td { border-bottom: 1px solid #E2E8F0; }
  td.amount, th.amount { text-align: right; }
  .total-row { display: flex; justify-content: space-between; align-items: center; padding: 20px; background: ${accent}; color: #FFFFFF; border-radius: 12px; margin-top: 8px; }
  .total-row .label { font-size: 12px; opacity: 0.8; letter-spacing: 0.5px; }
  .total-row .amount { font-size: 28px; font-weight: 800; }
  .notes { margin-top: 24px; padding: 16px; background: #F8FAFC; border-radius: 12px; font-size: 13px; color: #334155; }
  .footer { margin-top: 48px; text-align: center; font-size: 11px; color: #94A3B8; }
</style></head>
<body>
  <div class="header">
    <div>
      <h1 class="doc-title">${escapeHtml(args.title)}</h1>
      <div class="doc-number">${escapeHtml(args.number)}</div>
      ${businessLine}
    </div>
    ${logoBlock}
  </div>
  <div class="grid">
    ${clientBlock}
    <div>${metaRows}</div>
  </div>
  ${args.itemsHtml ?? ""}
  ${args.total ? `<div class="total-row"><div><div class="label">TOTAL</div></div><div class="amount">${escapeHtml(args.total)}</div></div>` : ""}
  ${args.notes ? `<div class="notes"><div class="muted">NOTES</div><div style="margin-top:4px;">${escapeHtml(args.notes)}</div></div>` : ""}
  <div class="footer">Generated by Lancely · From Client to Payment. One Place.</div>
</body></html>`;
}

async function generateAndShare(html: string, fileNameHint: string) {
  return generatePdfFromHtml(html, fileNameHint);
}

export async function generatePdfFromHtml(html: string, _fileNameHint: string): Promise<string> {
  if (Platform.OS === "web") {
    // expo-print on web doesn't produce a file URI; render the HTML in a Blob URL instead.
    if (typeof window === "undefined") return "";
    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    return URL.createObjectURL(blob);
  }
  const result = await Print.printToFileAsync({ html, base64: false });
  return result?.uri ?? "";
}

export async function sharePdfUri(uri: string, dialogTitle: string) {
  if (Platform.OS === "web") {
    if (typeof window !== "undefined") {
      window.open(uri, "_blank");
    }
    return;
  }
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle, UTI: "com.adobe.pdf" });
  }
}

export async function exportQuotePdf(
  quote: Quote,
  client: Client | null,
  opts: { logoUri?: string | null; businessName?: string | null; currency: string; accentColor?: string },
) {
  const fmt = (n: number) => `${opts.currency} ${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
  const itemsHtml = `
    <table>
      <thead><tr><th>Service</th><th>Description</th><th class="amount">Price</th></tr></thead>
      <tbody>
        ${quote.items
          .map(
            (it) =>
              `<tr><td><strong>${escapeHtml(it.service)}</strong></td><td>${escapeHtml(it.description || "")}</td><td class="amount">${escapeHtml(fmt(it.price))}</td></tr>`,
          )
          .join("")}
      </tbody>
    </table>`;
  const html = buildHtml({
    title: "Quote",
    number: quote.quote_number,
    meta: [
      { label: "Issued", value: new Date(quote.created_at).toLocaleDateString() },
      { label: "Status", value: quote.status.toUpperCase() },
    ],
    itemsHtml,
    total: fmt(quote.amount),
    notes: quote.notes,
    client,
    logoUri: opts.logoUri,
    businessName: opts.businessName,
    accentColor: opts.accentColor,
  });
  return generateAndShare(html, `Quote ${quote.quote_number}`);
}

export async function exportInvoicePdf(
  invoice: Invoice,
  client: Client | null,
  opts: { logoUri?: string | null; businessName?: string | null; currency: string; accentColor?: string },
) {
  const fmt = (n: number) => `${opts.currency} ${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
  const remaining = Math.max(invoice.amount - invoice.paid_amount, 0);
  const itemsHtml = `
    <table>
      <thead><tr><th>Description</th><th class="amount">Amount</th></tr></thead>
      <tbody>
        <tr>
          <td><strong>${escapeHtml(invoice.notes || "Service rendered")}</strong></td>
          <td class="amount">${escapeHtml(fmt(invoice.amount))}</td>
        </tr>
        ${
          invoice.paid_amount > 0
            ? `<tr><td>Paid to date</td><td class="amount">−${escapeHtml(fmt(invoice.paid_amount))}</td></tr>`
            : ""
        }
      </tbody>
    </table>`;
  const html = buildHtml({
    title: "Invoice",
    number: invoice.invoice_number,
    meta: [
      { label: "Issued", value: new Date(invoice.created_at).toLocaleDateString() },
      { label: "Due", value: new Date(invoice.due_date).toLocaleDateString() },
      { label: "Status", value: invoice.status.toUpperCase() },
    ],
    itemsHtml,
    total: fmt(remaining > 0 ? remaining : invoice.amount),
    notes: invoice.notes,
    client,
    logoUri: opts.logoUri,
    businessName: opts.businessName,
    accentColor: opts.accentColor,
  });
  return generateAndShare(html, `Invoice ${invoice.invoice_number}`);
}
